const crypto = require('crypto');

// Temporary storage (resets when Netlify function sleeps)
// For permanent storage, you'll eventually need a Database.
let activeKeys = ["TEST-KEY-123"]; 

exports.handler = async (event) => {
    // --- 1. KEY GENERATION (From your HTML Dashboard) ---
    if (event.httpMethod === "GET" && event.queryStringParameters.newKey) {
        const newKey = event.queryStringParameters.newKey;
        activeKeys.push(newKey); // Add the key generated by your HTML to the list
        
        return {
            statusCode: 200,
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({ status: "Registered", key: newKey })
        };
    }

    // --- 2. LOGIN VALIDATION (From your C++ Android App) ---
    if (event.httpMethod === "POST") {
        const params = new URLSearchParams(event.body);
        const user_key = params.get('user_key');
        const serial = params.get('serial'); 

        // Check if the key exists in our activeKeys list
        if (activeKeys.includes(user_key)) {
            const salt = "Vm8Lk7Uj2JmsjCPVPVjrLa7zgfx3uz9E";
            const authString = `PUBG-${user_key}-${serial}-${salt}`;
            const token = crypto.createHash('md5').update(authString).digest('hex');

            return {
                statusCode: 200,
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify({
                    status: true,
                    data: { token: token, rng: Math.floor(Date.now() / 1000) }
                })
            };
        }

        return {
            statusCode: 200,
            body: JSON.stringify({ status: false, reason: "Invalid Key" })
        };
    }

    return { statusCode: 400, body: "Bad Request" };
};
